### ISSUE TITLE
Add repository info to package.json

### ISSUE THREAD

**Issue by moltar** [AlexDid/iso-country-currency#2]
Right now there is no repository listed and it does not show up on NPM.

https://www.npmjs.com/package/iso-country-currency

<img width="437" alt="image" src="https://user-images.githubusercontent.com/491247/83323377-92c72c80-a288-11ea-9f03-e6c6a3345c44.png">

**Comment by OleksaDid** [comment]
fixed [PR#5](https://github.com/AlexDid/iso-country-currency/pull/5)
