### ISSUE TITLE
Add numericCode for each country

### ISSUE THREAD

**Issue by ghost** [AlexDid/iso-country-currency#23]
Can you please update this list with the currency numeric codes mentioned [here](https://en.wikipedia.org/wiki/ISO_4217)
For example
MXN <-> 484 

`  AD: {countryName: "Mexico", currency: "MXN", symbol: "MX$", numericCode: 484},`

**Comment by ghost** [comment]
@AlexDid  I raised a PR for the same
https://github.com/AlexDid/iso-country-currency/pull/24/files

**Comment by OleksaDid** [comment]
@mrugesh-jeeves thank you for the input!

I've merged it
