### ISSUE TITLE
Key is not defined error - getISOByParam, getParamByParam and other functions in angular 13 application

### ISSUE THREAD

**Issue by prakhar4321** [AlexDid/iso-country-currency#26]
Functions like getISOByParam have for loop in them - 
for(key in dataJson). Here 'key' variable is not declared and therefore it throws error. It will be really helpful if these for loops can be fixed. We are using this package in angular 13 application which generates mjs file. Angular 13 strictly throws error for undeclared variables.
Attaching the screenshot of the functions which need to be fixed.
![Screenshot 2023-01-21 at 15 44 27](https://user-images.githubusercontent.com/93765830/213872042-bed441af-cd9d-4571-9206-6edf35568bd4.png)
![Screenshot 2023-01-21 at 15 44 49](https://user-images.githubusercontent.com/93765830/213872051-cec4ca0d-e04d-401f-be4a-7792c8f56e0d.png)
![Screenshot 2023-01-21 at 15 46 35](https://user-images.githubusercontent.com/93765830/213872141-d77fde45-d0f1-4469-a383-ef64d9f04b55.png)

**Comment by OleksaDid** [comment]
fixed in v0.7.0
