### ISSUE TITLE
Getting data from old commits

### ISSUE THREAD

**Issue by usmanghani-em** [AlexDid/iso-country-currency#29]
I have installed the latest version 0.6.0, but it doesn't correspond to the latest commit. That's why I am getting old data. Kindly update version on npm to fix this. 

Got the following log when I tried ```yarn intall iso-country-currency@fcad24696ef16eeff67f1be3993e9f8850c4fdde```
```
Couldn't find any versions for "iso-country-currency" that matches "fcad24696ef16eeff67f1be3993e9f8850c4fdde"
```

**Comment by OleksaDid** [comment]
Hi @usmanghani-em,

I've updated the version, please let me know if the issue is fixed

**Comment by usmanghani-em** [comment]
@AlexDid fixed, thank you very much 👍🏻
